// user login/logout
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

// User logout
export const USER_LOGOUT = "USER_LOGOUT"

// user registration/signup
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

// user activation
export const USER_ACTIVATE_REQUEST = "USER_ACTIVATE_REQUEST"
export const USER_ACTIVATE_SUCCESS = "USER_ACTIVATE_SUCCESS"
export const USER_ACTIVATE_FAIL = "USER_ACTIVATE_FAIL"

// user reset_password
export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST"
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS"
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL"

// user reset_password_confirm
export const USER_RESET_PASSWORD_CONFIRM_REQUEST = "USER_RESET_PASSWORD_CONFIRM_REQUEST"
export const USER_RESET_PASSWORD_CONFIRM_SUCCESS = "USER_RESET_PASSWORD_CONFIRM_SUCCESS"
export const USER_RESET_PASSWORD_CONFIRM_FAIL = "USER_RESET_PASSWORD_CONFIRM_FAIL"

// get users
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'